package BibliographyLanguage.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenAspectBase;
import BibliographyLanguage.structure.LanguageConceptSwitch;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.text.rt.TextGenDescriptor;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.text.rt.TextGenModelOutline;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class TextGenAspectDescriptor extends TextGenAspectBase {
  private final LanguageConceptSwitch myIndex = new LanguageConceptSwitch();

  public TextGenAspectDescriptor() {
  }

  @Nullable
  @Override
  public TextGenDescriptor getDescriptor(@NotNull SAbstractConcept concept) {
    switch (myIndex.index(concept)) {
      case LanguageConceptSwitch.Author:
        return new Author_TextGen();
      case LanguageConceptSwitch.AuthorElement:
        return new AuthorElement_TextGen();
      case LanguageConceptSwitch.AuthorRef:
        return new AuthorRef_TextGen();
      case LanguageConceptSwitch.Bibliography:
        return new Bibliography_TextGen();
      case LanguageConceptSwitch.PublicationYearElement:
        return new PublicationYearElement_TextGen();
      case LanguageConceptSwitch.TitleElement:
        return new TitleElement_TextGen();
    }
    return null;
  }

  @Override
  public void breakdownToUnits(@NotNull TextGenModelOutline outline) {
    for (SNode root : outline.getModel().getRootNodes()) {
      if (root.getConcept().equals(CONCEPTS.Bibliography$DG)) {
        String fname = getFileName_Bibliography(root);
        String ext = getFileExtension_Bibliography(root);
        outline.registerTextUnit((ext == null ? fname : (fname + '.' + ext)), root);
        continue;
      }
    }
  }
  private static String getFileName_Bibliography(SNode node) {
    return node.getName();
  }
  private static String getFileExtension_Bibliography(SNode node) {
    return "bib";
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Bibliography$DG = MetaAdapterFactory.getConcept(0xbb75b69834bf4772L, 0xb67eb9c7faf0daabL, 0x125c2423bec6e346L, "BibliographyLanguage.structure.Bibliography");
  }
}
